#robot_name and joint_names determines the path library to use

#name of the robot that planning is being done for
string robot_name
#joints that planning is being done for
string[] joint_names

uint8 action
uint8 ACTION_STORE=1
uint8 ACTION_DELETE_PATH=2
uint8 ACTION_DELETE_LIBRARY=3

#path that was retrieved from the library: specify this if it needs to be compared to path_to_store to know if path_to_store should be stored in the library
trajectory_msgs/JointTrajectoryPoint[] retrieved_path

#path to store in the library if it is different enough from retrieved_path
trajectory_msgs/JointTrajectoryPoint[] path_to_store

#specify this if a path is to be deleted
int32 delete_id
---
uint8 result
uint8 FAILURE=0
uint8 SUCCESS=1

#message explaining a failure
string message
